language: python
os:
  - linux
  - osx
# OS seems to fail when installing python. not my fault.
matrix:
  allow_failures:
    - os: osx
python:
  - "2.7"
before_script:
 - chmod +x binaries
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: pytest